include:
  - project: '2ndwatch/gitlab-ci'
    ref: 'feature/npm-publish'
    file: '/aws-access.yml'
  - project: '2ndwatch/gitlab-ci'
    ref: 'feature/npm-publish'
    file: '/npm10.17.0.yml'

stages:
  - secrets
  - install
  - test
  - publish

secrets:
  stage: secrets
  extends: .aws-access-with-secrets
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+-.+$/
      - $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/

install:
  stage: install
  extends: .npm-install
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - node_modules
      - secrets
    policy: pull-push

lint:
  stage: test
  extends: .npm-lint
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - node_modules
      - secrets
    policy: pull

publish:
  stage: publish
  extends: .npm-publish
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - node_modules
      - secrets
    policy: pull
  before_script:
    - source secrets/secrets.txt