name: Publish package to GitHub Packages
on:
  release:
    types: [created]
jobs:
  publish:
    uses: harshparmar-fission/2w-estlint/.github/workflows/npm-publish.yml@master
    secrets: inherit
    with:
      release-version: ${{github.event.release.tag_name}}
